<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<!-- 2019-11-14
«How can I have Rocket Loader ignore specific JavaScripts?»
https://support.cloudflare.com/hc/en-us/articles/200169436 -->
<script data-cfasync='false'>
	var id = '<?= df_ejs(df_cfg('justuno_settings/options_interface/accid')); ?>';
	// 2019-11-14 «How to test valid UUID/GUID?»: https://stackoverflow.com/a/13653180
	if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id)) {
		console.log('JU_ERROR: Justuno Account ID (ACCID) Was Not Set Correctly...');
	}
	else {
		// 2019-11-14 https://support.justuno.com/install-justuno-general-embed-instructions
		window.ju_num = id;
		window.console.log(`ju_num loaded (${id})`);
		var r = 'juapp';
		window[r] = window[r] || function() {(window[r].q = window[r].q || []).push(arguments)};
		require(['//cdn.justuno.com/vck.js'], function(vck) {
			debugger;
		});
		/*window.asset_host = '//cdn.justuno.com/';
		(function(i, s, o, g, r, a, m) {
			i[r] = i[r] || function() {(i[r].q = i[r].q || []).push(arguments)};
			a = s.createElement(o);
			m = s.getElementsByTagName(o)[0];
			a.async = 1;
			a.src = g;
			m.parentNode.insertBefore(a, m);
		})(window, document, 'script', asset_host + 'vck.js', 'juapp');  */
	}
</script>
<?php /** 2019-11-14 @used-by view/frontend/web/js/magexsync.js */
if (df_is_catalog_product_view()) { ?>
	<script>
		setTimeout(function() {window.ju_MageProductView = <?= df_ejs([
			'PageID' => df_action_name(), 'ProductID' => df_product_current()->getId()
		]) ?>;}, 50);
	</script>
<?php } ?>
<script type='text/x-magento-init'>{"*" : {"Justuno_Jumagext/common": {"message": "magexsync done."}}}</script>