<?php
// 2019-11-13 {{block class="Magento\Framework\View\Element\Template" template="Justuno_Jumagext::embed.phtml"}}
/** @var \Magento\Framework\View\Element\Template $block */
$merchantId = df_cfg('justuno_settings/options_interface/accid'); /** @var string $merchantId */
if (preg_match("/^[{]?[0-9a-fA-F]{8}[-]?([0-9a-fA-F]{4}[-]?){3}[0-9a-fA-F]{12}[}]?$/", $merchantId)) { ?>
	<script>window.ju_num='<?= $merchantId ?>';</script>
	<?= df_widget('embed', '', ['message' => "ju_num loaded ({$block->escapeHtml(substr($merchantId, -6))})"]) ?>
<?php } else { ?>
	<script>console.log('JU_ERROR: Justuno Account ID (ACCID) Was Not Set Correctly...');</script>
<?php }
if (df_is_catalog_product_view()) { ?>
	<script>
		setTimeout(function(){
			window.ju_MageProductView = {
				CustomerID: '<?= !df_customer_logged_in() ? '' : df_customer_session()->getCustomerId() ?>',
				PageID: '<?= df_action_name() ?>',
				ProductID: '<?= df_product_current()->getId() ?>',
				StockQty: ''
			};
		},50);
	</script>
<?php } ?>