<?php
/**
 * shortcode for cms pages / blocks
 * {{block class="Justuno\Jumagext\Block\Frontend\Embed" template="Justuno_Jumagext::embed.phtml" }}
 *
 * @var Justuno\Jumagext\Block\Frontend\Embed $block
 */
$subject = $block->getValueACCID();
$pattern = "/^[{]?[0-9a-fA-F]{8}[-]?([0-9a-fA-F]{4}[-]?){3}[0-9a-fA-F]{12}[}]?$/";
if ($block->customerLoggedIn() == false) {
	$customerID = '';
}
if ($block->customerLoggedIn() == true){
	$customerID = $block->getCustomerID();
}
if (preg_match($pattern, $subject)) { ?>
	<script>window.ju_num='<?= $subject ?>';</script>
	<div
		data-mage-init='{"embed": {"message": "ju_num loaded (<?= $block->escapeHtml(substr($subject, -6)) ?>)"}}'></div>
<?php } else { ?>
	<script>console.log('JU_ERROR: Justuno Account ID (ACCID) Was Not Set Correctly...');</script>
<?php }
if ($block->getFullActionName() == 'catalog_product_view') { ?>
	<script>
		setTimeout(function(){
			window.ju_MageProductView = {
				PageID: '<?= $block->getFullActionName() ?>',
				ProductID: '<?= $block->getCurrentProductID(); ?>',
				CustomerID: '<?= $customerID ?>',
				StockQty: ''
			};
		},50);
	</script>
<?php } ?>