<?php
/**
 * shortcode for cms pages / blocks
 * {{block class='Justuno\M2\Block\Frontend\Success' template='Justuno_Jumagext::success.phtml' }}
 *
 * @var Justuno\M2\Block\Frontend\Success $block
 *
 *
 */
$orderId = $block->juGetOrderId();
$order = $block->juGetOrderById($orderId);
$currency = $block->getCurrentCurrencyCode();
?>
<script type='text/javascript'>
var cr = <?= $currency; ?>;
console.log(cr);
window.ju_order_id = <?= $orderId ?>;
window.ju_order_obj = {
	total: <?= $order->getBaseSubtotal() ?>,
	subtotal: <?= $order->getBaseGrandTotal() ?>,
	tax: <?= $order->getTaxAmount() ?>,
	shipping: <?= $order->getShippingAmount() ?>,
	currency: <?= $currency; ?>
};
</script>